plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.lizongying.mytv'
    compileSdk 34

    viewBinding {
        enabled = true
    }

    defaultConfig {
        applicationId "com.lizongying.mytv"
        minSdk 19
        multiDexEnabled true
        targetSdk 33
        versionCode project.findProperty('tvVersionCode')?.toInteger() ?: VersionCode()
        versionName project.findProperty('tvVersionName')?.toString() ?: VersionName()

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = 17
    }

}

static def VersionCode() {
    try {
        def p = "git describe --tags --always"
        def process = p.execute()
        process.waitFor()
        if (process.exitValue() != 0) throw new IllegalStateException("git describe failed")
        def replace = [v: "", ".": " ", "-": " "]
        def arr = (process.text.trim().replace(replace) + " 0").split(" ")
        def versionCode = arr[0].toInteger() * 16777216 + arr[1].toInteger() * 65536 + arr[2].toInteger() * 256 + arr[3].toInteger()
        println("VersionCode $versionCode")
        return versionCode
    } catch (Exception e) {
        throw new GradleException("Unable to derive versionCode from git tags", e)
    }
}

static def VersionName() {
    try {
        def process = "git describe --tags --always".execute()
        process.waitFor()
        if (process.exitValue() != 0) throw new IllegalStateException("git describe failed")
        return process.text.trim() - "v"
    } catch (Exception e) {
        throw new GradleException("Unable to derive versionName from git tags", e)
    }
}

dependencies {
    def media3_version = "1.3.1"

    implementation "androidx.media3:media3-ui:$media3_version"

    // For media playback using ExoPlayer
    implementation "androidx.media3:media3-exoplayer:$media3_version"

    // For HLS playback support with ExoPlayer
    implementation "androidx.media3:media3-exoplayer-hls:$media3_version"

    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    implementation 'androidx.leanback:leanback:1.2.0-alpha04'
    implementation 'com.github.bumptech.glide:glide:4.11.0'

    implementation 'androidx.core:core-ktx:1.13.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0-RC")

}
